# Generated by Django 3.0 on 2020-04-03 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200, null=True)),
                ('course_description', models.TextField(blank=True, null=True)),
                ('pic', models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to='')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modify_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=200, null=True)),
                ('quiz_description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modify_date', models.DateTimeField(auto_now=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=0, max_length=3)),
                ('age', models.PositiveIntegerField(default=0)),
                ('pic', models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to='')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modify_date', models.DateTimeField(auto_now=True, null=True)),
                ('skill', models.ManyToManyField(blank=True, null=True, to='tutorial.Skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.IntegerField(default=0, null=True)),
                ('wrong_answer', models.IntegerField(default=0, null=True)),
                ('none_answer', models.IntegerField(default=0, null=True)),
                ('total_qna', models.IntegerField(default=0, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.Quiz')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tutorial.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='QuizTaken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_enrollment', models.BooleanField(default=False, null=True)),
                ('quiz_taken', models.BooleanField(default=False, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.Quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.UserProfile'),
        ),
        migrations.CreateModel(
            name='Qna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(null=True)),
                ('answer', models.CharField(max_length=500, null=True)),
                ('option_1', models.CharField(max_length=500, null=True)),
                ('option_2', models.CharField(max_length=500, null=True)),
                ('option_3', models.CharField(max_length=500, null=True)),
                ('option_4', models.CharField(max_length=500, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='CourseEnroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_enrollment', models.BooleanField(default=False, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='skill',
            field=models.ManyToManyField(blank=True, null=True, to='tutorial.Skill'),
        ),
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.UserProfile'),
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_data', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modify_date', models.DateTimeField(auto_now=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.Course')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.Topic')),
            ],
        ),
    ]
