# Generated by Django 3.0 on 2020-04-03 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_auto_20200403_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qna',
            name='created_date',
        ),
    ]
