# Generated by Django 3.0 on 2020-04-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_remove_qna_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztaken',
            name='quiz_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quiztaken',
            name='user_enrollment',
            field=models.BooleanField(default=False),
        ),
    ]
