# Generated by Django 3.0 on 2020-04-05 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0004_auto_20200403_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userperformance',
            name='quiz',
        ),
    ]
