# Generated by Django 3.0 on 2020-04-05 12:20

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0005_remove_userperformance_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_data',
            field=tinymce.models.HTMLField(),
        ),
    ]
