# Generated by Django 3.0 on 2020-04-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0007_auto_20200405_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cid',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
