# Generated by Django 3.0 on 2020-04-06 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0008_course_cid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='cid',
        ),
    ]
