# Generated by Django 3.0 on 2020-04-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0016_skill_skill_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='slug',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
