# Generated by Django 3.0 on 2020-04-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0018_content_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, null=True)),
                ('feedack', models.TextField(blank=True, null=True)),
                ('notify', models.BooleanField(default=False)),
            ],
        ),
    ]
