# Generated by Django 3.0 on 2020-04-10 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0019_feedack'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedack',
            new_name='Feedback',
        ),
    ]
