# Generated by Django 3.0 on 2020-04-10 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0021_auto_20200410_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedack',
            new_name='feedback',
        ),
    ]
