# Generated by Django 3.0 on 2020-04-11 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0023_feedback_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='start_date',
        ),
    ]
