# Generated by Django 3.0 on 2020-04-11 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0024_remove_quiz_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='slug',
        ),
    ]
