# Generated by Django 3.0 on 2020-04-12 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0025_remove_content_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='rating',
            new_name='ratings',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starby', models.CharField(blank=True, max_length=200, null=True)),
                ('star1', models.PositiveIntegerField(default=0)),
                ('star2', models.PositiveIntegerField(default=0)),
                ('star3', models.PositiveIntegerField(default=0)),
                ('star4', models.PositiveIntegerField(default=0)),
                ('star5', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.UserProfile')),
            ],
        ),
    ]
