# Generated by Django 3.0 on 2020-04-12 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0026_auto_20200412_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ratings',
        ),
    ]
