# Generated by Django 3.0 on 2020-04-12 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0028_userprofile_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ratings',
        ),
    ]
