# Generated by Django 3.0 on 2020-04-12 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0030_auto_20200412_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='is_rating',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rating_by',
        ),
        migrations.AddField(
            model_name='rating',
            name='starby',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.UserProfile'),
        ),
    ]
