# Generated by Django 3.0 on 2020-04-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0032_auto_20200412_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='is_rating',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
