# Generated by Django 3.0 on 2020-04-12 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0033_rating_is_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='is_rating',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='starby',
        ),
        migrations.CreateModel(
            name='ByRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_rating', models.BooleanField(default=False)),
                ('rating_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.UserProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.Rating')),
            ],
        ),
    ]
