# Generated by Django 3.0 on 2020-04-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendindeed', '0002_auto_20200418_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='from_user',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='friend',
            name='to_user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
