# Generated by Django 3.0 on 2020-04-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendindeed', '0004_auto_20200418_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='from_info',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='information',
            name='to_info',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
