# Generated by Django 3.0 on 2020-04-17 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friendindeed', '0005_auto_20200418_0221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CRID', models.CharField(max_length=200, null=True)),
                ('from_member', models.PositiveIntegerField(default=0)),
                ('to_member', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='CRID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friendindeed.Member'),
        ),
    ]
