# Generated by Django 3.0 on 2020-04-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendindeed', '0006_auto_20200418_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='CRID',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
